baseurl      : "https://mikymod.github.io/"
languageCode : "en-us"
title        : "Mikymod's Blog"
theme        : "detox"

params:
    author       : "Michele Rossi"
    description  : "development blog"