baseurl         : "https://mikymod.github.io/"
languageCode    : "en-us"
title           : "GameCraft"
theme           : "detox"
disqusShortname : "mikymod-github-io"

params:
    author       : "Michele Rossi"
    description  : "A developer journey"
    twitter_name : "MikyM0D"
    github       : "mikymod"